development:
  adapter: mysql
  database: haystask_db
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql
  database: haystask_db_test
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
production:
  adapter: mysql
  database: haystask_db_pro
  username: root
  password: qwe123
  host: 127.0.0.1
  port: 3306
